'use client'

import React from 'react'

/**
 * API Documentation Dashboard
 *
 * Embeds Swagger UI for interactive API documentation.
 * Uses the OpenAPI spec generated by /api/docs endpoint.
 */
const ApiDocsDashboard: React.FC = () => {
  return (
    <div style={styles.container}>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <h1 style={styles.title}>API Documentation</h1>
          <p style={styles.subtitle}>Interactive API reference powered by OpenAPI 3.0</p>
        </div>
        <div style={styles.headerActions}>
          <a
            href="/api/docs"
            target="_blank"
            rel="noopener noreferrer"
            style={styles.jsonButton}
          >
            Download OpenAPI Spec
          </a>
        </div>
      </div>

      {/* Quick Links */}
      <div style={styles.quickLinks}>
        <a href="#products" style={styles.quickLink}>Products</a>
        <a href="#mobile" style={styles.quickLink}>Mobile</a>
        <a href="#users" style={styles.quickLink}>Users</a>
        <a href="#email" style={styles.quickLink}>Email</a>
        <a href="#analytics" style={styles.quickLink}>Analytics</a>
        <a href="#content" style={styles.quickLink}>Content</a>
        <a href="#scanning" style={styles.quickLink}>Scanning</a>
      </div>

      {/* Swagger UI Embed */}
      <div style={styles.swaggerContainer}>
        <iframe
          src="/api/docs?format=html"
          style={styles.iframe}
          title="API Documentation"
        />
      </div>

      {/* API Stats */}
      <div style={styles.statsRow}>
        <div style={styles.statCard}>
          <div style={styles.statValue}>80+</div>
          <div style={styles.statLabel}>Total Endpoints</div>
        </div>
        <div style={styles.statCard}>
          <div style={styles.statValue}>7</div>
          <div style={styles.statLabel}>API Categories</div>
        </div>
        <div style={styles.statCard}>
          <div style={styles.statValue}>v1.0</div>
          <div style={styles.statLabel}>API Version</div>
        </div>
        <div style={styles.statCard}>
          <div style={styles.statValue}>OpenAPI 3.0</div>
          <div style={styles.statLabel}>Specification</div>
        </div>
      </div>

      {/* Integration Examples */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Quick Start</h2>
        <div style={styles.codeExamples}>
          <div style={styles.codeBlock}>
            <h3 style={styles.codeTitle}>JavaScript/TypeScript</h3>
            <pre style={styles.code}>{`// Fetch products
const response = await fetch('https://theproductreport.org/api/products?limit=10');
const data = await response.json();
console.log(data.docs);`}</pre>
          </div>
          <div style={styles.codeBlock}>
            <h3 style={styles.codeTitle}>cURL</h3>
            <pre style={styles.code}>{`# Barcode lookup
curl "https://theproductreport.org/api/scanner/lookup?barcode=012345678901"

# With authentication
curl -H "Authorization: Bearer YOUR_TOKEN" \\
  "https://theproductreport.org/api/users/me"`}</pre>
          </div>
        </div>
      </div>

      {/* Rate Limits Info */}
      <div style={styles.infoSection}>
        <h3 style={styles.infoTitle}>Rate Limiting</h3>
        <div style={styles.rateLimits}>
          <div style={styles.rateLimit}>
            <span style={styles.rateLimitEndpoint}>Standard Endpoints</span>
            <span style={styles.rateLimitValue}>100 req/min</span>
          </div>
          <div style={styles.rateLimit}>
            <span style={styles.rateLimitEndpoint}>Search/Scan Endpoints</span>
            <span style={styles.rateLimitValue}>30 req/min</span>
          </div>
          <div style={styles.rateLimit}>
            <span style={styles.rateLimitEndpoint}>Admin Endpoints</span>
            <span style={styles.rateLimitValue}>60 req/min</span>
          </div>
        </div>
      </div>
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: '24px',
    maxWidth: '1400px',
    margin: '0 auto',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '24px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  title: {
    margin: 0,
    fontSize: '28px',
    fontWeight: 700,
    color: '#fff',
  },
  subtitle: {
    margin: '4px 0 0',
    fontSize: '14px',
    color: '#71717a',
  },
  headerActions: {
    display: 'flex',
    gap: '12px',
  },
  jsonButton: {
    padding: '10px 20px',
    background: 'rgba(59, 130, 246, 0.15)',
    border: '1px solid rgba(59, 130, 246, 0.3)',
    borderRadius: '6px',
    color: '#3b82f6',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: 500,
  },
  quickLinks: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '24px',
  },
  quickLink: {
    padding: '6px 12px',
    background: '#27272a',
    borderRadius: '4px',
    color: '#a1a1aa',
    textDecoration: 'none',
    fontSize: '13px',
  },
  swaggerContainer: {
    background: '#fff',
    borderRadius: '12px',
    overflow: 'hidden',
    marginBottom: '24px',
    border: '1px solid #27272a',
  },
  iframe: {
    width: '100%',
    height: '800px',
    border: 'none',
  },
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '16px',
    marginBottom: '32px',
  },
  statCard: {
    background: '#18181b',
    border: '1px solid #27272a',
    borderRadius: '12px',
    padding: '20px',
    textAlign: 'center',
  },
  statValue: {
    fontSize: '24px',
    fontWeight: 700,
    color: '#3b82f6',
  },
  statLabel: {
    fontSize: '13px',
    color: '#71717a',
    marginTop: '4px',
  },
  section: {
    marginBottom: '32px',
  },
  sectionTitle: {
    margin: '0 0 16px',
    fontSize: '18px',
    fontWeight: 600,
    color: '#e4e4e7',
  },
  codeExamples: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))',
    gap: '16px',
  },
  codeBlock: {
    background: '#18181b',
    border: '1px solid #27272a',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  codeTitle: {
    margin: 0,
    padding: '12px 16px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#a1a1aa',
    background: '#27272a',
    borderBottom: '1px solid #3f3f46',
  },
  code: {
    margin: 0,
    padding: '16px',
    fontSize: '13px',
    color: '#e4e4e7',
    fontFamily: 'Monaco, Consolas, monospace',
    lineHeight: 1.5,
    overflow: 'auto',
  },
  infoSection: {
    background: '#18181b',
    border: '1px solid #27272a',
    borderRadius: '12px',
    padding: '20px',
  },
  infoTitle: {
    margin: '0 0 16px',
    fontSize: '16px',
    fontWeight: 600,
    color: '#e4e4e7',
  },
  rateLimits: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  rateLimit: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 0',
    borderBottom: '1px solid #27272a',
  },
  rateLimitEndpoint: {
    color: '#a1a1aa',
    fontSize: '14px',
  },
  rateLimitValue: {
    color: '#22c55e',
    fontSize: '14px',
    fontWeight: 600,
  },
}

export default ApiDocsDashboard
