/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    articles: Article;
    videos: Video;
    media: Media;
    categories: Category;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'youtube-settings': YoutubeSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'youtube-settings': YoutubeSettingsSelect<false> | YoutubeSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  brand: string;
  category?: (number | null) | Category;
  /**
   * Use this OR upload an image below
   */
  imageUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Auto-calculated from ratings below
   */
  overallScore?: number | null;
  /**
   * Auto-calculated rank within category
   */
  rankInCategory?: number | null;
  /**
   * Overall score is auto-calculated: Performance 30%, Reliability 25%, Value 25%, Features 20%
   */
  ratings?: {
    performance?: number | null;
    reliability?: number | null;
    valueForMoney?: number | null;
    features?: number | null;
  };
  badges?: {
    /**
     * Top product in this category
     */
    isBestInCategory?: boolean | null;
    /**
     * Editor-approved quality product
     */
    isRecommended?: boolean | null;
    /**
     * Best price-to-performance ratio
     */
    isBestValue?: boolean | null;
    /**
     * Exceptional product (rare)
     */
    isEditorsChoice?: boolean | null;
  };
  status?: ('draft' | 'testing' | 'writing' | 'review' | 'published') | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  pros?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Brief overview for cards and previews
   */
  summary?: string | null;
  fullReview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  purchaseLinks?:
    | {
        retailer: string;
        url: string;
        price?: string | null;
        isAffiliate?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Link related products for comparison
   */
  comparedWith?: (number | Product)[] | null;
  testingInfo?: {
    reviewDate?: string | null;
    lastTestedDate?: string | null;
    versionTested?: string | null;
    /**
     * Notes about changes since last review
     */
    updateNotes?: string | null;
  };
  isBestBuy?: boolean | null;
  isRecommended?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Used in URLs (e.g., "smartphones")
   */
  slug: string;
  /**
   * Brief description for SEO and category pages
   */
  description?: string | null;
  /**
   * Use emoji (📱) or Ionicons name
   */
  icon?: string | null;
  /**
   * Create sub-categories (e.g., Electronics > Smartphones)
   */
  parent?: (number | null) | Category;
  /**
   * Auto-calculated
   */
  productCount?: number | null;
  imageUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-friendly slug (e.g., "best-headphones-2024")
   */
  slug: string;
  /**
   * Short summary shown in article cards (150-200 chars)
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL to external cover image
   */
  imageUrl?: string | null;
  image?: (number | null) | Media;
  category: 'buying-guide' | 'investigation' | 'deals' | 'behind-the-scenes' | 'health' | 'news' | 'comparison';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Products mentioned in this article
   */
  relatedProducts?: (number | Product)[] | null;
  author: string;
  publishedAt: string;
  /**
   * Estimated reading time in minutes
   */
  readTime: number;
  status?: ('draft' | 'review' | 'published') | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * The ID from the YouTube URL (e.g., "dQw4w9WgXcQ" from youtube.com/watch?v=dQw4w9WgXcQ)
   */
  youtubeVideoId: string;
  /**
   * Leave empty to auto-fetch from YouTube
   */
  thumbnailUrl?: string | null;
  description?: string | null;
  /**
   * Video duration in seconds
   */
  duration?: number | null;
  category?: (number | null) | Category;
  /**
   * Link to the product being reviewed in this video
   */
  relatedProduct?: (number | null) | Product;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  viewCount?: number | null;
  isFeatured?: boolean | null;
  /**
   * Was this video imported from YouTube automatically?
   */
  isAutoImported?: boolean | null;
  /**
   * When this video was last synced from YouTube
   */
  youtubeImportedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  subscriptionStatus?: ('free' | 'trial' | 'premium' | 'cancelled') | null;
  /**
   * When the 7-day trial started
   */
  trialStartDate?: string | null;
  /**
   * When the 7-day trial ends
   */
  trialEndDate?: string | null;
  /**
   * Products viewed this month (5 free limit)
   */
  productViewsThisMonth?: number | null;
  /**
   * When product views counter resets
   */
  productViewsResetDate?: string | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  revenuecatUserId?: string | null;
  /**
   * Google OAuth user ID
   */
  googleId?: string | null;
  /**
   * Apple Sign-In user ID
   */
  appleId?: string | null;
  privacyConsent?: {
    /**
     * User consented to data processing for service operation
     */
    dataProcessingConsent?: boolean | null;
    /**
     * When consent was given
     */
    consentDate?: string | null;
    /**
     * User opted in to receive marketing emails
     */
    marketingOptIn?: boolean | null;
  };
  /**
   * Array of saved product IDs
   */
  savedProductIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of saved article IDs
   */
  savedArticleIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  category?: T;
  imageUrl?: T;
  image?: T;
  overallScore?: T;
  rankInCategory?: T;
  ratings?:
    | T
    | {
        performance?: T;
        reliability?: T;
        valueForMoney?: T;
        features?: T;
      };
  badges?:
    | T
    | {
        isBestInCategory?: T;
        isRecommended?: T;
        isBestValue?: T;
        isEditorsChoice?: T;
      };
  status?: T;
  priceRange?: T;
  pros?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  summary?: T;
  fullReview?: T;
  purchaseLinks?:
    | T
    | {
        retailer?: T;
        url?: T;
        price?: T;
        isAffiliate?: T;
        id?: T;
      };
  comparedWith?: T;
  testingInfo?:
    | T
    | {
        reviewDate?: T;
        lastTestedDate?: T;
        versionTested?: T;
        updateNotes?: T;
      };
  isBestBuy?: T;
  isRecommended?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  imageUrl?: T;
  image?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedProducts?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeVideoId?: T;
  thumbnailUrl?: T;
  description?: T;
  duration?: T;
  category?: T;
  relatedProduct?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  sortOrder?: T;
  viewCount?: T;
  isFeatured?: T;
  isAutoImported?: T;
  youtubeImportedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  parent?: T;
  productCount?: T;
  imageUrl?: T;
  image?: T;
  featured?: T;
  sortOrder?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  subscriptionStatus?: T;
  trialStartDate?: T;
  trialEndDate?: T;
  productViewsThisMonth?: T;
  productViewsResetDate?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  revenuecatUserId?: T;
  googleId?: T;
  appleId?: T;
  privacyConsent?:
    | T
    | {
        dataProcessingConsent?: T;
        consentDate?: T;
        marketingOptIn?: T;
      };
  savedProductIds?: T;
  savedArticleIds?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'articles';
                value: number | Article;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'articles';
                value: number | Article;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-settings".
 */
export interface YoutubeSetting {
  id: number;
  /**
   * Your YouTube channel ID (found at youtube.com/account_advanced)
   */
  channelId?: string | null;
  /**
   * Get from Google Cloud Console with YouTube Data API v3 enabled
   */
  apiKey?: string | null;
  /**
   * Automatically sync videos daily
   */
  autoSyncEnabled?: boolean | null;
  /**
   * Maximum number of videos to import per sync
   */
  maxVideosToSync?: number | null;
  /**
   * Only import YouTube Shorts (videos under 60 seconds)
   */
  shortsOnly?: boolean | null;
  /**
   * When videos were last synced from YouTube
   */
  lastSyncAt?: string | null;
  lastSyncStatus?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-settings_select".
 */
export interface YoutubeSettingsSelect<T extends boolean = true> {
  channelId?: T;
  apiKey?: T;
  autoSyncEnabled?: T;
  maxVideosToSync?: T;
  shortsOnly?: T;
  lastSyncAt?: T;
  lastSyncStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}