/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    products: Product;
    articles: Article;
    videos: Video;
    media: Media;
    categories: Category;
    'investigation-polls': InvestigationPoll;
    'sponsored-test-requests': SponsoredTestRequest;
    ingredients: Ingredient;
    'verdict-rules': VerdictRule;
    'audit-log': AuditLog;
    users: User;
    'price-history': PriceHistory;
    brands: Brand;
    'regulatory-changes': RegulatoryChange;
    'user-submissions': UserSubmission;
    'device-fingerprints': DeviceFingerprint;
    'product-unlocks': ProductUnlock;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'investigation-polls': InvestigationPollsSelect<false> | InvestigationPollsSelect<true>;
    'sponsored-test-requests': SponsoredTestRequestsSelect<false> | SponsoredTestRequestsSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    'verdict-rules': VerdictRulesSelect<false> | VerdictRulesSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'price-history': PriceHistorySelect<false> | PriceHistorySelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'regulatory-changes': RegulatoryChangesSelect<false> | RegulatoryChangesSelect<true>;
    'user-submissions': UserSubmissionsSelect<false> | UserSubmissionsSelect<true>;
    'device-fingerprints': DeviceFingerprintsSelect<false> | DeviceFingerprintsSelect<true>;
    'product-unlocks': ProductUnlocksSelect<false> | ProductUnlocksSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'youtube-settings': YoutubeSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'youtube-settings': YoutubeSettingsSelect<false> | YoutubeSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | StatsBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Leave empty to auto-create.
   */
  slug?: string | null;
  /**
   * Brief description for SEO and category pages
   */
  description?: string | null;
  /**
   * Auto-selected based on category name. Override with any Lucide icon name
   */
  icon?: string | null;
  /**
   * Create sub-categories (e.g., Electronics > Smartphones)
   */
  parent?: (number | null) | Category;
  /**
   * Auto-calculated
   */
  productCount?: number | null;
  imageUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  /**
   * Harmful ingredients inherited from parent category
   */
  inheritedFromParent?: boolean | null;
  /**
   * Created by AI from video analysis
   */
  aiSuggested?: boolean | null;
  /**
   * Video ID or source that suggested this category
   */
  aiSource?: string | null;
  /**
   * Ingredients flagged in research videos
   */
  harmfulIngredients?:
    | {
        ingredient: string;
        /**
         * Why it should be avoided
         */
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What to look for in good products
   */
  qualityIndicators?:
    | {
        indicator: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * AI-extracted research findings from video transcripts
   */
  researchNotes?: string | null;
  /**
   * When category was last enriched with research
   */
  lastEnrichedAt?: string | null;
  /**
   * Auto-calculated: Best product to showcase for this category
   */
  featuredProduct?: (number | null) | Product;
  /**
   * Cached image URL of the featured product
   */
  featuredProductImage?: string | null;
  /**
   * When featured product was last recalculated
   */
  featuredProductUpdatedAt?: string | null;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  brand: string;
  slug?: string | null;
  category?: (number | null) | Category;
  /**
   * Will be auto-created immediately (hierarchical supported)
   */
  pendingCategoryName?: string | null;
  /**
   * Use this OR upload an image below
   */
  imageUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Auto-set when background is removed. Prevents duplicate processing.
   */
  backgroundRemoved?: boolean | null;
  /**
   * Final verdict on this product
   */
  verdict: 'recommend' | 'avoid';
  /**
   * Brief explanation of why this verdict was given
   */
  verdictReason?: string | null;
  /**
   * System-calculated from ingredients + rules
   */
  autoVerdict?: ('recommend' | 'avoid') | null;
  /**
   * Enable to manually set verdict different from auto-calculated
   */
  verdictOverride?: boolean | null;
  /**
   * Required: explain why you are overriding the auto-verdict
   */
  verdictOverrideReason?: string | null;
  verdictOverriddenBy?: (number | null) | User;
  verdictOverriddenAt?: string | null;
  /**
   * Name of VerdictRule(s) that set the verdict
   */
  ruleApplied?: string | null;
  /**
   * Auto-populated from raw text, or manually link
   */
  ingredientsList?: (number | Ingredient)[] | null;
  /**
   * Paste ingredients list - will auto-parse and link to Ingredients collection
   */
  ingredientsRaw?: string | null;
  /**
   * Ingredients that could not be auto-matched (need manual research)
   */
  unmatchedIngredients?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Universal Product Code for barcode scanning
   */
  upc?: string | null;
  /**
   * Amazon Standard Identification Number (10 characters). Used to auto-generate affiliate links.
   */
  amazonAsin?: string | null;
  /**
   * TikTok, Amazon, or other URL where data was extracted
   */
  sourceUrl?: string | null;
  /**
   * YouTube video from Videos collection (if applicable)
   */
  sourceVideo?: (number | null) | Video;
  /**
   * Number of sources that mentioned this product
   */
  sourceCount?: number | null;
  /**
   * AI confidence in extraction accuracy
   */
  aiConfidence?: ('high' | 'medium' | 'low') | null;
  /**
   * How the AI extracted this product
   */
  aiSourceType?: ('transcript' | 'video_watching' | 'profile' | 'manual') | null;
  /**
   * Times mentioned in source video
   */
  aiMentions?: number | null;
  /**
   * System-detected conflicts (blocks publishing if unresolved)
   */
  conflicts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Auto-calculated from last tested date
   */
  freshnessStatus?: ('fresh' | 'needs_review' | 'stale') | null;
  status?: ('ai_draft' | 'draft' | 'testing' | 'writing' | 'review' | 'published') | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  pros?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Brief overview for cards and previews
   */
  summary?: string | null;
  fullReview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  purchaseLinks?:
    | {
        retailer: string;
        url: string;
        price?: string | null;
        isAffiliate?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Link related products for comparison
   */
  comparedWith?: (number | Product)[] | null;
  testingInfo?: {
    reviewDate?: string | null;
    lastTestedDate?: string | null;
    versionTested?: string | null;
    /**
     * Notes about changes since last review
     */
    updateNotes?: string | null;
  };
  /**
   * Award badges displayed on product cards and pages
   */
  badges?: {
    /**
     * 🥇 Mark this product as the #1 pick for its category. Only ONE product per category should have this enabled.
     */
    isBestOverall?: boolean | null;
    /**
     * Featured product for this category
     */
    isBestInCategory?: boolean | null;
    /**
     * Staff recommended product
     */
    isRecommended?: boolean | null;
    /**
     * Best price-to-quality ratio
     */
    isBestValue?: boolean | null;
    /**
     * Selected as editor's top pick
     */
    isEditorsChoice?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * User role determines CMS permissions. Product Editors can add/edit products and categories but cannot delete.
   */
  role?: ('admin' | 'product_editor' | 'user') | null;
  /**
   * Legacy admin flag - use role field instead
   */
  isAdmin?: boolean | null;
  subscriptionStatus?: ('free' | 'trial' | 'premium' | 'cancelled') | null;
  /**
   * When the 7-day trial started
   */
  trialStartDate?: string | null;
  /**
   * When the 7-day trial ends
   */
  trialEndDate?: string | null;
  /**
   * Products viewed this month (5 free limit)
   */
  productViewsThisMonth?: number | null;
  /**
   * When product views counter resets
   */
  productViewsResetDate?: string | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  revenuecatUserId?: string | null;
  /**
   * Google OAuth user ID
   */
  googleId?: string | null;
  /**
   * Apple Sign-In user ID
   */
  appleId?: string | null;
  privacyConsent?: {
    /**
     * User consented to data processing for service operation
     */
    dataProcessingConsent?: boolean | null;
    /**
     * When consent was given
     */
    consentDate?: string | null;
    /**
     * User opted in to receive marketing emails
     */
    marketingOptIn?: boolean | null;
  };
  /**
   * Array of saved product IDs
   */
  savedProductIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of saved article IDs
   */
  savedArticleIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Categories this user is watching for updates
   */
  watchlistCategories?: (number | Category)[] | null;
  /**
   * Ingredients this user wants to avoid. Structure: [{ ingredientId, ingredientName, reason?, dateAdded }]
   */
  ingredientWatchlist?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Receive weekly digest emails with new products and community highlights
   */
  weeklyDigestEnabled?: boolean | null;
  /**
   * User state in the One-Shot Engine funnel
   */
  memberState?: ('virgin' | 'trial' | 'member') | null;
  /**
   * Number of free product unlocks remaining
   */
  freeUnlockCredits?: number | null;
  /**
   * Array of permanently unlocked product IDs
   */
  unlockedProducts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Devices associated with this user
   */
  deviceFingerprints?: (number | DeviceFingerprint)[] | null;
  /**
   * Total unlocks across all time
   */
  totalUnlocks?: number | null;
  /**
   * When the last product was unlocked
   */
  lastUnlockAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Device fingerprints for One-Shot unlock tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-fingerprints".
 */
export interface DeviceFingerprint {
  id: number;
  /**
   * FingerprintJS visitor ID hash
   */
  fingerprintHash: string;
  /**
   * Associated user account (if any)
   */
  user?: (number | null) | User;
  /**
   * Browser name and version
   */
  browser?: string | null;
  /**
   * Operating system
   */
  os?: string | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet') | null;
  firstSeenAt: string;
  lastSeenAt?: string | null;
  /**
   * Number of free unlocks used on this device
   */
  unlockCreditsUsed?: number | null;
  /**
   * Country from IP (for fraud detection)
   */
  ipCountry?: string | null;
  /**
   * Block this device from unlocking
   */
  isBanned?: boolean | null;
  /**
   * Why this device was banned
   */
  banReason?: string | null;
  /**
   * Flagged for review (multiple emails, VPN, etc.)
   */
  suspiciousActivity?: boolean | null;
  /**
   * List of email addresses used with this fingerprint
   */
  emailsUsed?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ingredient database with verdicts that cascade to products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  /**
   * Primary name (e.g., "Red Dye 40")
   */
  name: string;
  /**
   * Other names this ingredient goes by
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Final verdict on this ingredient
   */
  verdict: 'safe' | 'caution' | 'avoid' | 'unknown';
  /**
   * Brief explanation of the verdict
   */
  reason?: string | null;
  category?:
    | (
        | 'artificial_colors'
        | 'artificial_sweeteners'
        | 'preservatives'
        | 'emulsifiers'
        | 'heavy_metals'
        | 'pesticides'
        | 'vitamins_minerals'
        | 'proteins'
        | 'fats_oils'
        | 'sugars'
        | 'fibers'
        | 'other'
      )
    | null;
  /**
   * Which product categories is this ingredient relevant to?
   */
  productCategories?: (number | Category)[] | null;
  /**
   * Videos, studies, or reports that informed this verdict
   */
  sources?:
    | {
        type?: ('video' | 'study' | 'lab_report' | 'government') | null;
        reference?: string | null;
        /**
         * Brief note about this source
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main video where this ingredient was discussed
   */
  sourceVideo?: (number | null) | Video;
  /**
   * When AVOID, automatically flag products containing this
   */
  autoFlagProducts?: boolean | null;
  /**
   * Products currently flagged due to this ingredient
   */
  flaggedProductCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * The ID from the YouTube URL (e.g., "dQw4w9WgXcQ" from youtube.com/watch?v=dQw4w9WgXcQ)
   */
  youtubeVideoId: string;
  /**
   * Leave empty to auto-fetch from YouTube
   */
  thumbnailUrl?: string | null;
  description?: string | null;
  /**
   * Video duration in seconds
   */
  duration?: number | null;
  category?: (number | null) | Category;
  /**
   * Link to the product being reviewed in this video
   */
  relatedProduct?: (number | null) | Product;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  viewCount?: number | null;
  isFeatured?: boolean | null;
  /**
   * Shorts will appear in the mobile Browse tab
   */
  videoType?: ('short' | 'longform') | null;
  /**
   * Was this video imported from YouTube automatically?
   */
  isAutoImported?: boolean | null;
  /**
   * When this video was last synced from YouTube
   */
  youtubeImportedAt?: string | null;
  /**
   * Stored transcript from YouTube captions (auto-populated on analysis)
   */
  transcript?: string | null;
  /**
   * When transcript was last fetched
   */
  transcriptUpdatedAt?: string | null;
  /**
   * When AI last analyzed this video
   */
  analyzedAt?: string | null;
  /**
   * Products that were created from analyzing this video
   */
  extractedProducts?: (number | Product)[] | null;
  /**
   * Ingredients discussed in this video
   */
  extractedIngredients?: (number | Ingredient)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  stats?:
    | {
        label: string;
        valueType?: ('manual' | 'products' | 'users' | 'categories' | 'videos' | 'brands') | null;
        manualValue?: string | null;
        suffix?: string | null;
        icon?: ('flask' | 'users' | 'shield' | 'check' | 'star' | 'chart') | null;
        id?: string | null;
      }[]
    | null;
  backgroundColor?: ('default' | 'dark' | 'primary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-friendly slug (e.g., "best-headphones-2024")
   */
  slug: string;
  /**
   * Short summary shown in article cards (50-300 chars). No placeholder text allowed.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL to external cover image
   */
  imageUrl?: string | null;
  image?: (number | null) | Media;
  category: 'buying-guide' | 'investigation' | 'deals' | 'behind-the-scenes' | 'health' | 'news' | 'comparison';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Products mentioned in this article
   */
  relatedProducts?: (number | Product)[] | null;
  author: string;
  publishedAt: string;
  /**
   * Estimated reading time in minutes
   */
  readTime: number;
  status?: ('draft' | 'review' | 'published') | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investigation-polls".
 */
export interface InvestigationPoll {
  id: number;
  /**
   * e.g., "What should we investigate next?"
   */
  title: string;
  /**
   * Additional context for the poll
   */
  description?: string | null;
  status: 'active' | 'closed';
  /**
   * Leave empty for no end date
   */
  endDate?: string | null;
  options: {
    name: string;
    description?: string | null;
    votes?: number | null;
    id?: string | null;
  }[];
  /**
   * Map of userId -> optionIndex tracking who voted
   */
  voters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totalVotes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User-sponsored product test requests ($149 each)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsored-test-requests".
 */
export interface SponsoredTestRequest {
  id: number;
  /**
   * The product the customer wants tested
   */
  productName: string;
  /**
   * Customer email from Stripe checkout
   */
  email: string;
  /**
   * Stripe payment intent ID for this sponsorship
   */
  stripePaymentId?: string | null;
  /**
   * Current status of the test request
   */
  status: 'pending' | 'testing' | 'complete' | 'refunded';
  /**
   * Internal notes about this request
   */
  notes?: string | null;
  /**
   * URL to the completed PDF report (once testing is done)
   */
  reportUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Automated rules for product verdicts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verdict-rules".
 */
export interface VerdictRule {
  id: number;
  /**
   * e.g., "Flag products with Red Dye 40"
   */
  name: string;
  /**
   * What this rule does and why
   */
  description?: string | null;
  /**
   * What triggers this rule
   */
  conditionType: 'contains_ingredient' | 'missing_ingredient' | 'ingredient_verdict' | 'category_match';
  /**
   * Which ingredients trigger this rule
   */
  ingredientCondition?: (number | Ingredient)[] | null;
  /**
   * Match based on ingredient verdicts
   */
  ingredientVerdictCondition?: ('avoid' | 'caution' | 'safe_only') | null;
  /**
   * Apply only to these categories
   */
  categoryCondition?: (number | Category)[] | null;
  /**
   * What happens when rule matches
   */
  action: 'set_avoid' | 'set_caution' | 'set_recommend' | 'block_publish' | 'warn_only';
  /**
   * Message shown when rule triggers
   */
  warningMessage?: string | null;
  isActive?: boolean | null;
  /**
   * Higher priority rules run first
   */
  priority?: number | null;
  /**
   * How many times this rule has been applied
   */
  appliedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable audit trail of all AI and system actions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action:
    | 'ai_product_created'
    | 'ai_ingredient_parsed'
    | 'ai_verdict_set'
    | 'rule_applied'
    | 'ingredient_cascade'
    | 'manual_override'
    | 'product_merged'
    | 'category_created'
    | 'image_enriched'
    | 'poll_closed'
    | 'article_generated'
    | 'conflict_detected'
    | 'freshness_check';
  sourceType?: ('youtube' | 'tiktok' | 'amazon' | 'web_url' | 'barcode' | 'manual' | 'system' | 'rule') | null;
  /**
   * Video ID, URL, UPC, or rule ID
   */
  sourceId?: string | null;
  sourceUrl?: string | null;
  targetCollection?: ('products' | 'ingredients' | 'categories' | 'videos' | 'articles' | 'investigation-polls') | null;
  targetId?: number | null;
  /**
   * Human-readable name for quick reference
   */
  targetName?: string | null;
  /**
   * State before the action (for updates)
   */
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * State after the action
   */
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Extra context (rule details, AI response, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g., gemini-2.0-flash
   */
  aiModel?: string | null;
  /**
   * AI confidence percentage if available
   */
  confidence?: number | null;
  /**
   * User who triggered this action (null for system)
   */
  performedBy?: (number | null) | User;
  success?: boolean | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historical price and size data for shrinkflation/skimpflation detection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history".
 */
export interface PriceHistory {
  id: number;
  /**
   * The product this price record is for
   */
  product: number | Product;
  /**
   * Price in USD (e.g., 4.99)
   */
  price: number;
  /**
   * Sale price if on sale
   */
  salePrice?: number | null;
  /**
   * Price per oz/unit for comparison
   */
  pricePerUnit?: number | null;
  /**
   * Package size as displayed (e.g., "12 oz", "500ml")
   */
  size?: string | null;
  /**
   * Normalized size in oz for comparison
   */
  sizeNormalized?: number | null;
  /**
   * Number of units in package (for multipacks)
   */
  unitCount?: number | null;
  retailer: 'amazon' | 'walmart' | 'target' | 'costco' | 'kroger' | 'whole_foods' | 'instacart' | 'manual';
  /**
   * URL where price was captured
   */
  sourceUrl?: string | null;
  capturedAt: string;
  /**
   * Ingredient list at time of capture (for skimpflation detection)
   */
  ingredientsSnapshot?: string | null;
  /**
   * Number of ingredients at capture time
   */
  ingredientCount?: number | null;
  /**
   * System detected an anomaly in this record
   */
  anomalyDetected?: boolean | null;
  anomalyType?: ('price_increase' | 'shrinkflation' | 'skimpflation' | 'double_whammy') | null;
  /**
   * Detailed anomaly analysis data
   */
  anomalyDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Brand database with trust scoring and parent company tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  /**
   * Primary brand name (e.g., "Cheerios", "Tide")
   */
  name: string;
  /**
   * Other names or spellings for this brand
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL-friendly slug
   */
  slug?: string | null;
  /**
   * Parent corporation (e.g., "General Mills", "Procter & Gamble")
   */
  parentCompany?: string | null;
  /**
   * Calculated trust score (0-100)
   */
  trustScore?: number | null;
  trustGrade?: ('A' | 'B' | 'C' | 'D' | 'F') | null;
  trustScoreLastCalculated?: string | null;
  /**
   * Individual factors contributing to trust score
   */
  scoreBreakdown?: {
    /**
     * Score based on ingredient safety across products
     */
    ingredientQuality?: number | null;
    /**
     * Score based on recall frequency and severity
     */
    recallHistory?: number | null;
    /**
     * Score based on ingredient disclosure practices
     */
    transparency?: number | null;
    /**
     * Score based on formulation consistency (no skimpflation)
     */
    consistency?: number | null;
    /**
     * Score based on response to issues/complaints
     */
    responsiveness?: number | null;
  };
  /**
   * Total products from this brand in database
   */
  productCount?: number | null;
  /**
   * Products with AVOID verdict
   */
  avoidCount?: number | null;
  /**
   * Total recalls associated with this brand
   */
  recallCount?: number | null;
  /**
   * Historical recalls associated with this brand
   */
  recalls?:
    | {
        recallNumber: string;
        date?: string | null;
        reason?: string | null;
        severity?: ('class_i' | 'class_ii' | 'class_iii') | null;
        source?: ('fda' | 'cpsc' | 'usda' | 'voluntary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Official brand website
   */
  website?: string | null;
  logo?: (number | null) | Media;
  /**
   * Brief description of the brand
   */
  description?: string | null;
  /**
   * Product categories this brand operates in
   */
  categories?: (number | Category)[] | null;
  /**
   * Internal notes about this brand
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Regulatory updates that affect ingredients or products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-changes".
 */
export interface RegulatoryChange {
  id: number;
  /**
   * Short descriptive title for this regulatory change
   */
  title: string;
  /**
   * Official reference number (e.g., FDA-2024-N-1234)
   */
  referenceId?: string | null;
  source:
    | 'fda'
    | 'usda'
    | 'epa'
    | 'prop65'
    | 'efsa'
    | 'eu_commission'
    | 'health_canada'
    | 'who_iarc'
    | 'codex'
    | 'other';
  /**
   * Link to official regulatory document
   */
  sourceUrl?: string | null;
  changeType: 'ban' | 'restriction' | 'limit' | 'labeling' | 'warning' | 'approval' | 'review' | 'guideline';
  severity?: ('critical' | 'high' | 'medium' | 'low') | null;
  /**
   * When the change was announced
   */
  announcedDate?: string | null;
  /**
   * When the change takes effect
   */
  effectiveDate?: string | null;
  /**
   * Deadline for industry compliance
   */
  complianceDeadline?: string | null;
  /**
   * Ingredients directly affected by this regulation
   */
  affectedIngredients?: (number | Ingredient)[] | null;
  /**
   * Product categories this regulation applies to
   */
  affectedCategories?: (number | Category)[] | null;
  /**
   * Substances mentioned that may not be in our ingredient database yet
   */
  affectedSubstances?:
    | {
        name: string;
        casNumber?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Plain-language summary of the regulatory change
   */
  summary?: string | null;
  /**
   * How this affects products in our database
   */
  impact?: string | null;
  recommendedAction?: ('update_avoid' | 'add_warning' | 'review' | 'monitor' | 'none') | null;
  status: 'pending' | 'analyzing' | 'published' | 'actioned' | 'dismissed';
  /**
   * Article generated from this regulatory change
   */
  generatedArticle?: (number | null) | Article;
  /**
   * Raw data from source API/scrape
   */
  rawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User-submitted product scans, tips, and reports
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-submissions".
 */
export interface UserSubmission {
  id: number;
  type: 'product_scan' | 'tip' | 'reaction_report' | 'correction' | 'product_request';
  /**
   * Email for follow-up and points tracking
   */
  submitterEmail?: string | null;
  /**
   * Display name (optional)
   */
  submitterName?: string | null;
  /**
   * For spam prevention
   */
  submitterIp?: string | null;
  /**
   * Existing product this submission relates to
   */
  product?: (number | null) | Product;
  images?:
    | {
        image: number | Media;
        imageType?: ('front' | 'back' | 'ingredients' | 'nutrition' | 'barcode' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * User-provided description or details
   */
  content?: string | null;
  /**
   * UPC/EAN barcode if scanned
   */
  barcode?: string | null;
  reactionDetails?: {
    symptoms?: ('skin' | 'digestive' | 'headache' | 'allergic' | 'behavioral' | 'other')[] | null;
    severity?: ('mild' | 'moderate' | 'severe' | 'medical') | null;
    suspectedIngredient?: string | null;
  };
  /**
   * AI-extracted data from images
   */
  extractedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * AI confidence in extraction (0-100)
   */
  aiConfidence?: number | null;
  status: 'pending' | 'reviewing' | 'verified' | 'rejected' | 'duplicate' | 'spam';
  /**
   * Internal notes from review
   */
  moderatorNotes?: string | null;
  productRequestDetails?: {
    requestedProductName: string;
    requestedBrand?: string | null;
    /**
     * Link to product page (Amazon, retailer, etc.)
     */
    productUrl?: string | null;
    reasonForRequest?: string | null;
  };
  /**
   * Number of community votes
   */
  voteCount?: number | null;
  /**
   * Array of user IDs who voted
   */
  voters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pointsAwarded?: number | null;
  /**
   * Feature this submission (bonus points)
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable record of all product unlocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-unlocks".
 */
export interface ProductUnlock {
  id: number;
  /**
   * User who unlocked the product
   */
  user?: (number | null) | User;
  /**
   * Device used for unlock
   */
  deviceFingerprint?: (number | null) | DeviceFingerprint;
  /**
   * Email provided at unlock time (for guests)
   */
  email?: string | null;
  /**
   * Product that was unlocked
   */
  product: number | Product;
  unlockType: 'free_credit' | 'subscription' | 'admin_grant';
  /**
   * Which archetype card was unlocked
   */
  archetypeShown?: ('best_value' | 'premium_pick' | 'hidden_gem') | null;
  unlockedAt: string;
  /**
   * The AVOID product that triggered alternatives view
   */
  sourceProductId?: number | null;
  /**
   * Browser session ID for funnel tracking
   */
  sessionId?: string | null;
  /**
   * UTM source or referrer URL
   */
  referralSource?: string | null;
  /**
   * Did this user later subscribe?
   */
  convertedToSubscription?: boolean | null;
  conversionDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'investigation-polls';
        value: number | InvestigationPoll;
      } | null)
    | ({
        relationTo: 'sponsored-test-requests';
        value: number | SponsoredTestRequest;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'verdict-rules';
        value: number | VerdictRule;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'price-history';
        value: number | PriceHistory;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'regulatory-changes';
        value: number | RegulatoryChange;
      } | null)
    | ({
        relationTo: 'user-submissions';
        value: number | UserSubmission;
      } | null)
    | ({
        relationTo: 'device-fingerprints';
        value: number | DeviceFingerprint;
      } | null)
    | ({
        relationTo: 'product-unlocks';
        value: number | ProductUnlock;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        label?: T;
        valueType?: T;
        manualValue?: T;
        suffix?: T;
        icon?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  slug?: T;
  category?: T;
  pendingCategoryName?: T;
  imageUrl?: T;
  image?: T;
  backgroundRemoved?: T;
  verdict?: T;
  verdictReason?: T;
  autoVerdict?: T;
  verdictOverride?: T;
  verdictOverrideReason?: T;
  verdictOverriddenBy?: T;
  verdictOverriddenAt?: T;
  ruleApplied?: T;
  ingredientsList?: T;
  ingredientsRaw?: T;
  unmatchedIngredients?:
    | T
    | {
        name?: T;
        id?: T;
      };
  upc?: T;
  amazonAsin?: T;
  sourceUrl?: T;
  sourceVideo?: T;
  sourceCount?: T;
  aiConfidence?: T;
  aiSourceType?: T;
  aiMentions?: T;
  conflicts?: T;
  freshnessStatus?: T;
  status?: T;
  priceRange?: T;
  pros?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  summary?: T;
  fullReview?: T;
  purchaseLinks?:
    | T
    | {
        retailer?: T;
        url?: T;
        price?: T;
        isAffiliate?: T;
        id?: T;
      };
  comparedWith?: T;
  testingInfo?:
    | T
    | {
        reviewDate?: T;
        lastTestedDate?: T;
        versionTested?: T;
        updateNotes?: T;
      };
  badges?:
    | T
    | {
        isBestOverall?: T;
        isBestInCategory?: T;
        isRecommended?: T;
        isBestValue?: T;
        isEditorsChoice?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  imageUrl?: T;
  image?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedProducts?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeVideoId?: T;
  thumbnailUrl?: T;
  description?: T;
  duration?: T;
  category?: T;
  relatedProduct?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  sortOrder?: T;
  viewCount?: T;
  isFeatured?: T;
  videoType?: T;
  isAutoImported?: T;
  youtubeImportedAt?: T;
  transcript?: T;
  transcriptUpdatedAt?: T;
  analyzedAt?: T;
  extractedProducts?: T;
  extractedIngredients?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  parent?: T;
  productCount?: T;
  imageUrl?: T;
  image?: T;
  featured?: T;
  sortOrder?: T;
  inheritedFromParent?: T;
  aiSuggested?: T;
  aiSource?: T;
  harmfulIngredients?:
    | T
    | {
        ingredient?: T;
        reason?: T;
        id?: T;
      };
  qualityIndicators?:
    | T
    | {
        indicator?: T;
        description?: T;
        id?: T;
      };
  researchNotes?: T;
  lastEnrichedAt?: T;
  featuredProduct?: T;
  featuredProductImage?: T;
  featuredProductUpdatedAt?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investigation-polls_select".
 */
export interface InvestigationPollsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  endDate?: T;
  options?:
    | T
    | {
        name?: T;
        description?: T;
        votes?: T;
        id?: T;
      };
  voters?: T;
  totalVotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsored-test-requests_select".
 */
export interface SponsoredTestRequestsSelect<T extends boolean = true> {
  productName?: T;
  email?: T;
  stripePaymentId?: T;
  status?: T;
  notes?: T;
  reportUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  verdict?: T;
  reason?: T;
  category?: T;
  productCategories?: T;
  sources?:
    | T
    | {
        type?: T;
        reference?: T;
        notes?: T;
        id?: T;
      };
  sourceVideo?: T;
  autoFlagProducts?: T;
  flaggedProductCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verdict-rules_select".
 */
export interface VerdictRulesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  conditionType?: T;
  ingredientCondition?: T;
  ingredientVerdictCondition?: T;
  categoryCondition?: T;
  action?: T;
  warningMessage?: T;
  isActive?: T;
  priority?: T;
  appliedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  sourceType?: T;
  sourceId?: T;
  sourceUrl?: T;
  targetCollection?: T;
  targetId?: T;
  targetName?: T;
  before?: T;
  after?: T;
  metadata?: T;
  aiModel?: T;
  confidence?: T;
  performedBy?: T;
  success?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isAdmin?: T;
  subscriptionStatus?: T;
  trialStartDate?: T;
  trialEndDate?: T;
  productViewsThisMonth?: T;
  productViewsResetDate?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  revenuecatUserId?: T;
  googleId?: T;
  appleId?: T;
  privacyConsent?:
    | T
    | {
        dataProcessingConsent?: T;
        consentDate?: T;
        marketingOptIn?: T;
      };
  savedProductIds?: T;
  savedArticleIds?: T;
  watchlistCategories?: T;
  ingredientWatchlist?: T;
  weeklyDigestEnabled?: T;
  memberState?: T;
  freeUnlockCredits?: T;
  unlockedProducts?: T;
  deviceFingerprints?: T;
  totalUnlocks?: T;
  lastUnlockAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history_select".
 */
export interface PriceHistorySelect<T extends boolean = true> {
  product?: T;
  price?: T;
  salePrice?: T;
  pricePerUnit?: T;
  size?: T;
  sizeNormalized?: T;
  unitCount?: T;
  retailer?: T;
  sourceUrl?: T;
  capturedAt?: T;
  ingredientsSnapshot?: T;
  ingredientCount?: T;
  anomalyDetected?: T;
  anomalyType?: T;
  anomalyDetails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  slug?: T;
  parentCompany?: T;
  trustScore?: T;
  trustGrade?: T;
  trustScoreLastCalculated?: T;
  scoreBreakdown?:
    | T
    | {
        ingredientQuality?: T;
        recallHistory?: T;
        transparency?: T;
        consistency?: T;
        responsiveness?: T;
      };
  productCount?: T;
  avoidCount?: T;
  recallCount?: T;
  recalls?:
    | T
    | {
        recallNumber?: T;
        date?: T;
        reason?: T;
        severity?: T;
        source?: T;
        id?: T;
      };
  website?: T;
  logo?: T;
  description?: T;
  categories?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-changes_select".
 */
export interface RegulatoryChangesSelect<T extends boolean = true> {
  title?: T;
  referenceId?: T;
  source?: T;
  sourceUrl?: T;
  changeType?: T;
  severity?: T;
  announcedDate?: T;
  effectiveDate?: T;
  complianceDeadline?: T;
  affectedIngredients?: T;
  affectedCategories?: T;
  affectedSubstances?:
    | T
    | {
        name?: T;
        casNumber?: T;
        id?: T;
      };
  summary?: T;
  impact?: T;
  recommendedAction?: T;
  status?: T;
  generatedArticle?: T;
  rawData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-submissions_select".
 */
export interface UserSubmissionsSelect<T extends boolean = true> {
  type?: T;
  submitterEmail?: T;
  submitterName?: T;
  submitterIp?: T;
  product?: T;
  images?:
    | T
    | {
        image?: T;
        imageType?: T;
        id?: T;
      };
  content?: T;
  barcode?: T;
  reactionDetails?:
    | T
    | {
        symptoms?: T;
        severity?: T;
        suspectedIngredient?: T;
      };
  extractedData?: T;
  aiConfidence?: T;
  status?: T;
  moderatorNotes?: T;
  productRequestDetails?:
    | T
    | {
        requestedProductName?: T;
        requestedBrand?: T;
        productUrl?: T;
        reasonForRequest?: T;
      };
  voteCount?: T;
  voters?: T;
  pointsAwarded?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-fingerprints_select".
 */
export interface DeviceFingerprintsSelect<T extends boolean = true> {
  fingerprintHash?: T;
  user?: T;
  browser?: T;
  os?: T;
  deviceType?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  unlockCreditsUsed?: T;
  ipCountry?: T;
  isBanned?: T;
  banReason?: T;
  suspiciousActivity?: T;
  emailsUsed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-unlocks_select".
 */
export interface ProductUnlocksSelect<T extends boolean = true> {
  user?: T;
  deviceFingerprint?: T;
  email?: T;
  product?: T;
  unlockType?: T;
  archetypeShown?: T;
  unlockedAt?: T;
  sourceProductId?: T;
  sessionId?: T;
  referralSource?: T;
  convertedToSubscription?: T;
  conversionDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-settings".
 */
export interface YoutubeSetting {
  id: number;
  /**
   * Your YouTube channel ID (found at youtube.com/account_advanced)
   */
  channelId?: string | null;
  /**
   * Get from Google Cloud Console with YouTube Data API v3 enabled
   */
  apiKey?: string | null;
  /**
   * Automatically sync videos daily
   */
  autoSyncEnabled?: boolean | null;
  /**
   * Maximum number of videos to import per sync
   */
  maxVideosToSync?: number | null;
  /**
   * Only import YouTube Shorts (videos under 60 seconds)
   */
  shortsOnly?: boolean | null;
  /**
   * When videos were last synced from YouTube
   */
  lastSyncAt?: string | null;
  lastSyncStatus?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  affiliateSettings?: {
    /**
     * Your Amazon Associates tag (e.g., "yoursite-20"). Used to generate affiliate links.
     */
    amazonAffiliateTag?: string | null;
    /**
     * Disclosure text shown near affiliate links
     */
    affiliateDisclosure?: string | null;
    /**
     * Show affiliate links on product pages
     */
    enableAffiliateLinks?: boolean | null;
  };
  siteInfo?: {
    siteName?: string | null;
    siteDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-settings_select".
 */
export interface YoutubeSettingsSelect<T extends boolean = true> {
  channelId?: T;
  apiKey?: T;
  autoSyncEnabled?: T;
  maxVideosToSync?: T;
  shortsOnly?: T;
  lastSyncAt?: T;
  lastSyncStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  affiliateSettings?:
    | T
    | {
        amazonAffiliateTag?: T;
        affiliateDisclosure?: T;
        enableAffiliateLinks?: T;
      };
  siteInfo?:
    | T
    | {
        siteName?: T;
        siteDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}